### ISSUE TITLE
Develop more detailed requirements for fine-grained permissions

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#1098] opened 2024-07-11 19:44 UTC

**Comment by bickelj** [comment] 2024-07-15 15:31
There are a number of stories regarding "my" data and "my" organization already present. Examples:
https://github.com/orgs/PhilanthropyDataCommons/projects/4/views/6?sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=58424322&sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=Status&pane=issue&itemId=39313981
https://github.com/PhilanthropyDataCommons/meta/issues/14
https://github.com/PhilanthropyDataCommons/meta/issues/11

A significant one here: https://github.com/PhilanthropyDataCommons/meta/issues/48

**Comment by slifty** [comment] 2024-07-15 16:12
Whoops I just realized that https://github.com/PhilanthropyDataCommons/service/issues/1093 existed and this may have been a duplicate 😬

@bickelj should we close this as a dupe and move the above links over to 1093?

**Comment by bickelj** [comment] 2024-07-15 16:42
@slifty No objection. We can keep them split ("develop detailed requirements" versus "think") or we can combine them. To avoid proliferation we can close this as duplicate of #1093.

**Closed by bickelj** 2024-07-15 16:42 UTC

**Comment by slifty** [comment] 2024-07-15 18:33
Ha ironically I think when I said `develop` in this issue I meant `design` (once we have a plan I do think we should make n issue / issues for implementation)
