### ISSUE TITLE
Add Applicant always setting opted_in to false

### ISSUE THREAD

**Issue by mortimal1** [PhilanthropyDataCommons/service#128] opened 2022-11-29 16:12 UTC
opted_in field is always being set to false despite what's provided in the API

**Comment by bickelj** [comment] 2022-11-29 17:59
Thank you for reporting this issue. I have reproduced it.

**Comment by slifty** [comment] 2022-11-29 18:06
Hey all -- so just to provide some context this is actually the currently intended behavior, though I think there's room for a discussion about it (and regardless I appreciate that the API documentation is at best misleading).

For context: PDC as a project still needs to define some more robust requirements around applicant ownership of their data.

In lieu of those decisions the thinking was that for now -- from a system design perspective -- the only entity that can opt a given applicant into the PDC is the applicant themselves.  This means that API clients cannot specify that an applicant opted into the PDC; rather, we would eventually have some type of opt in system wherein an applicant is contacted by the PDC and asked if they want to opt in.

Now, regardless of whether that is the correct decision... the Swagger spec is flawed because it lists `opted_in` as a writable field -- the thinking was that in some contexts it would be be.  I'll take on figuring out the right fix for this.

**Comment by mortimal1** [comment] 2022-11-29 18:47
If this is the case, will the PDC be assigning the external id that can be used to query if the applicant has opted in and/or where the applicant would provide their external id when submitting the proposal and if provided, could it be assumed that they opted in? I would assume this id would be a UUID because a single applicant may exist across many different foundations? Or do you consider the applicant as unique to the opportunity? and if that were the case if I query for an applicant using an external id, wouldn't I need the opportunity id as well?

**Comment by slifty** [comment] 2022-11-29 22:18
These are excellent questions!

Regarding applicants / external ID: the current design is treating applicants as "universal" / spanning all proposals they submit(the external ID is intended to be their TIN / EIN), so one would be able to look them up in terms of that value (so the assignment would be at a government level rather than by a GMS or PDC).

Regarding the opt-in: we don't have answers just yet, and I think it will be the job of the PDC commons to collectively hash out some of those governance decisions.

For the pilot PDC is not really doing *anything* related to opt-in / opt-out (I suspect the the best solution to this issue in the short term will be to simply remove that field from the API specification entirely / mark it as read only for now).  The original inclusion in the documentation really was just to prompt the discussion among non-technical stakeholders in the context of the demo.

For an example of where data permissions might go: the discussion might include exploration of different levels of granularity of control (e.g. someone might only want their data made available in certain situations, or to certain organizations, etc), and require more advanced configuration than a single boolean flag.

**Comment by slifty** [comment] 2023-10-24 19:26
I believe the original issue raised here was addressed in the conversation -- I'm also going to reference #396 since some schema questions were raised in the followup.

**Closed by slifty** 2023-10-24 19:26 UTC
