### ISSUE TITLE
Field review: `proposal_name` vs `proposal_title`

### ISSUE THREAD

**Issue by jasonaowen** [PhilanthropyDataCommons/service#284] opened 2023-04-01 00:50 UTC
What is the intended difference between `proposal_name` and `proposal_title`? Will there be any proposals that have both, and have different values for each?

https://github.com/PhilanthropyDataCommons/service/blob/50b31ab1c6a6056bf05e99a22cad68b1ea7de891/src/database/seeds/0001-insert-canonical_fields.sql#L123-L124

**Comment by bickelj** [comment] 2023-04-03 18:43
At least two funders have a distinct project title from a grant or proposal name (or title).

As an aside, I'm not sure where we should be tracking data issues but given the centrality to the PDC I suppose here is a good spot until we make a better one.

**Comment by slifty** [comment] 2023-04-03 19:39
Might it help to rename one of these fields to be "Project Title" (rather than two versions of "Proposal Name")?

**Comment by bickelj** [comment] 2023-04-03 19:46
@slifty Perhaps. It is (as always) going to depend on what folks see in actual proposal data versus what folks expect to see.

**Comment by slifty** [comment] 2023-04-03 23:13
I think our role here would be to document the *intended purpose* of the canonical fields and make those purposes as useful and clear as possible -- we control the fields, not the proposal data or the application forms.

We shouldn't make redundant canonical fields (these two are very confusing to me as currently named)!  The field mapping I think is the part that would depend more on the actual proposal data? (e.g. we'd ask "Does that data align with our intent behind the canonical field we chose to map it to.")

**Comment by bickelj** [comment] 2023-05-02 16:40
@slifty This SQL ran in prod:
```
-- Distinguish Project Title from Proposal Name by adding Project
UPDATE canonical_fields
  SET label = 'Proposal Project Title',
    short_code = 'proposal_project_title'
  WHERE short_code = 'proposal_title';
```
So there is another word distinguishing the "Proposal Name" from the "Proposal Project Title". I made a note in the base fields sheet to the effect of "use 'Proposal Name' if you are unsure." What a project title is at the moment: another field for those funders who have a second field for a project title separate from a grant/request/proposal title or name.

As for whether that resolves the issue is yet to be determined.

**Comment by slifty** [comment] 2023-05-02 17:06
Makes sense -- it sounds like the next step is to raise it at our next checkin meeting.

**Comment by reefdog** [comment] 2023-05-16 16:26
@bickelj Ooh, this brings up a really good point: when we do these kinds of semantic remappings, does the Data Viewer UI need to communicate this?

The current mockup (which is due for a rethink given all we've learned in the past few months) assumes we'll just need to show the changes in a given field's values.

![Proposal Versions](https://github.com/PhilanthropyDataCommons/service/assets/4731/06495a95-648e-4995-bfc4-55f40275ccbd)

There's no design for showing "this field became this field" (or "these fields merged into this one"). You'd just have two rows: one for the old field (which was blank in the latest version), and one for the new field (which seemed to appear out of thin air in the latest version).

It's early to hammer out these details, but if we think this sort of data remapping will be important to show to users, we'll have to consider how to capture that in the PDC and expose it via the API. I'll add it to today's agenda in case we have time.

**Comment by bickelj** [comment] 2023-05-16 16:37
I don't think we have a formal way to represent the "this field became that field" in the back-end explicitly so the implicit two-row thing you mentioned may be the best we can (or should) do. The data might exist, e.g. in the migration tables, git log, or pg logs but those are not the means we'd want to use to formally expose changes over time via the API.

I assume the above is for proposals and not for application forms, though, right? An additional view for changes to the application form might give better detail than solely proposal changes.

**Comment by reefdog** [comment] 2023-05-16 17:25
Correct, that's a proposal. The viewer doesn't currently expose the application form concept.

You very well may be right that tracking the history (or rather, exposing it via the API, which is what I really mean) is a lift too large for us to tackle anytime soon. It'd be good to find out if anyone is expecting that.

**Comment by jasonaowen** [comment] 2023-05-17 00:28
I feel like we came up with three different definitions for these two fields, and none of us took adequate notes during today's call, so I'm not sure I'm summarizing correctly:

- the name of the proposal as entered by the applicant on the form
- the name of the funder budget(?) the funder assigns the proposal
- the name of the applicant project(?) the applicant organizes multiple proposals under

Is that accurate? @bickelj @jim-mcgowan

**Comment by jim-mcgowan** [comment] 2023-05-17 04:13
@jasonaowen: Pretty much! Here's a little extra definition:

- The name of a proposal/project/application for which an applicant is seeking funding. Note that the majority of applications are not actually proposals; they are simply applicants responding to direct invitations to seek funding. Thus, we would do well to find a better term than **proposal**.
- The name proposal/project/application assigned by a grantmaker for internal use. This is not common but it is prevalent enough that it must be considered.
- The name of a campaign/proposal/project for which the allocated/requested funding is only a portion of a larger effort.* Often, grantmakers will want to see how their funding fits into the overall goal of the applicant and may base there decision on how the additional resources are to be secured.

**Comment by bickelj** [comment] 2023-05-17 16:26
@jasonaowen The high-level conclusion I thought we reached was this: `proposal_name` is relatively simple and clear. Use it. The others (potentially two others) are relatively complex and cloudy (see Jim's reply above). We may not even need a Base Field for the internal use assigned by funder/grantmaker.

**Comment by slifty** [comment] 2024-07-19 17:36
This kind of change is no longer a developer task -- base fields are data driven and can be edited via API / interfaces.

**Closed by slifty** 2024-07-19 17:36 UTC
